### ISSUE TITLE
Readable and actionable Fiscal Data Package documentation

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/datapackage-fiscal#4]
# Description

Who is the audience for the spec? Ensure the spec text speaks to them.

See [here](https://github.com/openspending/fiscal-data-package/issues/72) and [here](https://github.com/openspending/fiscal-data-package/issues/71) for more context.

# Tasks

- [ ] Present draft structure for review
- [ ] Present draft text for review
- [ ] Ship for v1-rc1

**Comment by Vanuan** [comment]
Old discussion is unavailable

**Comment by stevage** [comment]
Personally, I think the main audience for the specs is anyone who will be generating conformant files. If you're just creating one or two files, you'll use the data packager. But if you need to generate files on the fly, then you need it.

Btw, having just revisited some of this stuff for the first time in a while, I found it surprisingly confusing and difficult dealing with all the different layers of spec. FDP, Table Schema, Tabular Data Resource, Data Package. Probably this would be improved by further iterations of reducing verbage, linking to the right place at the right time, etc - but maybe some bigger reorganisation required too.

**Comment by pwalsh** [comment]
@akariv 

Can you link to the current text working document of the v1 spec in whole, which, while still in need of editing and structure, takes a completely different approach to the v0.3 spec and is much more friendly and readable. Would be good to get some feedback even in current state.

**Comment by akariv** [comment]
This is the current working draft of the spec: https://hackmd.io/BwNgpgrCDGDsBMBaAhtALARkWsPEE5posR8RxgAzffWfDIA=?view

All feedback would be most welcome!
